import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/layout/Navbar/Navbar";
import Footer from "@/components/layout/Footer/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const geistMont = localFont({
  src: "./fonts/Montserrat-VariableFont_wght.ttf",
  variable: "--font-geist-mont",
  weight: "100 900",
});

export const metadata = {
  title: "PrimeWave - Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${geistMont.variable} antialiased font-montserrat`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
